// <auto-generated />
namespace GasSolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_CustomGas_Scripts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_CustomGas_Scripts));
        
        string IMigrationMetadata.Id
        {
            get { return "201711270523561_Update_CustomGas_Scripts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
